services:
  - type: web
    name: telegram-ads-assistant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: META_API_VERSION
        value: v20.0
      - key: CONFIRM_REQUIRED
        value: "true"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: META_ACCESS_TOKEN
        sync: false
      - key: META_AD_ACCOUNT_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_IMAGE_MODEL
        value: gpt-image-1.5
      - key: OPENAI_IMAGE_SIZE
        value: 1024x1024
      - key: IMAGE_PROVIDER
        value: openai
      - key: GEMINI_IMAGE_MODEL
        value: gemini-2.5-flash-image
      - key: GOOGLE_DRIVE_FOLDER_ID
        value: 11T-9iJ-Q7WL6SnKXZ7cPzGw1FjTmPEeV
      - key: GOOGLE_SHEET_ID
        value: 1CjQsVzTAJSBXjhZGD3iwailQ7tTzUc4KjoV7fukywTk
      - key: GOOGLE_MEDIA_FOLDER_ID
        value: 1HqojclzE5iaPVovTGa-_A43P5oLx8CLw
      - key: DEFAULT_CTA
        value: 'Chỉ cần bình luận "QUAN TÂM", Sư Tử Vàng sẽ hỗ trợ bạn tạo mẫu đồng phục theo thiết kế riêng miễn phí, tối ưu theo môi trường làm việc thực tế cho doanh nghiệp, giúp đội ngũ mặc chuyên nghiệp, an toàn, thoải mái hơn và nâng cao hình ảnh thương hiệu.'
      - key: DEFAULT_FOOTER
        value: '-----------------------------------------\nĐỒNG PHỤC CAO CẤP SƯ TỬ VÀNG\nĐịa chỉ: 81 Trần Mai Ninh, P. Bảy Hiền, (Quận Tân Bình cũ), TP.HCM\nWebsite: dongphucsutuvang.com\nHotline: 091 111 4866\n-----------------------------------------\n#SuTuVang #DongPhucCaoCap #Vanhoadoanhnghiep\n#Hinhanhthuonghieu #maydongphuc #dongphucchatluong #GoldenLion #PremiumWorkwear #DongPhucDoanhNghiep #KienTaoThuongHieu #DongPhucCaoCap'
      - key: COMPOSIO_API_KEY
        sync: false
      - key: COMPOSIO_CONNECTED_ACCOUNT_ID
        sync: false
      - key: COMPOSIO_GOOGLESHEETS_CONNECTED_ACCOUNT_ID
        value: ca_L610ErQ5oEIz
      - key: COMPOSIO_USER_ID
        value: user_rz7pm
      - key: COMPOSIO_FACEBOOK_PAGE_ID
        sync: false
      - key: COMPOSIO_FACEBOOK_POST_ACTION_ID
        value: FACEBOOK_CREATE_POST
      - key: COMPOSIO_FACEBOOK_PHOTO_ACTION_ID
        value: FACEBOOK_CREATE_PHOTO_POST
      - key: COMPOSIO_LINKEDIN_POST_ACTION_ID
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
